In [6]:
!pip install numpy

In [7]:
!pip install advertools

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 326.3/326.3 kB 2.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 290.1/290.1 kB 17.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 27.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.8/247.8 kB 20.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.6/97.6 kB 9.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.6/74.6 kB 6.8 MB/s eta 0:00:00


In [8]:
!pip install pandas

In [9]:
import advertools

In [10]:
import pandas

In [11]:
import numpy


In [18]:
import numpy as np

# creating a 1D array from a list
arr1 = np.array([1, 2, 3, 4, 5]) # Removed extra indentation here
print(arr1)

# Creating a 2D array from a list of lists
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [19]:
# Creating an array of zeros
zeros = np.zeros((3, 4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
# Creating an array of ones
ones = np.ones((2, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
# Creating an array with a range of values
range_arr = np.arange(10, 20, 2)
print(range_arr)

[10 12 14 16 18]


In [22]:
# Creating an array with random values
random_arr = np.random.rand(3, 3)
print(random_arr)

[[0.29098438 0.7112998  0.27527475]
 [0.87390059 0.1123775  0.52081895]
 [0.52559368 0.18488759 0.00129514]]


Basic Array Operation- Element-Wise Operation

In [25]:
for i in arr1:
  print(i+2)

3
4
5
6
7


In [23]:
arr = np.array([1, 2, 3, 4, 5])

# Element-Wise addition
print(arr + 2)

[3 4 5 6 7]


In [26]:
# Element - Wise multiplication
print (arr * 2)

[ 2  4  6  8 10]


In [27]:
# Element -Wise division
print (arr / 2)

[0.5 1.  1.5 2.  2.5]


In [28]:
# element -wise subtration
print (arr - 2)

[-1  0  1  2  3]


Basic array operations

In [29]:
arr = np.array([1, 2, 3, 4, 5])

# Square root
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [30]:
# Exponential
print(np.exp(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [31]:
# Logarithm
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [32]:
# Sine
print(np.sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


Indexing and Slicing-Indexing

In [33]:
arr = np.array([1, 2, 3, 4, 5])

# Accessing element
print(arr[0])# first element
print(arr[-1])# last element

1
5


Indexing and slicing- Slicing

In [34]:
arr = np.array([1, 2, 3, 4, 5])

# Slicing array
print(arr[1:4]) # element from index 1 o 3
print(arr[:3]) # first three element
print(arr[2:]) # element from index 2 to the end

[2 3 4]
[1 2 3]
[3 4 5]


Indexing and Slicing -Advanced Indexing

In [36]:
arr = np.array([1, 2, 3, 4, 5])

# Boolean indexing
print(arr[arr > 3])
indice =[0, 2, 4]
print(arr[indice])

[4 5]
[1 3 5]


Reshaping and transposing- Reshaping arrays

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshaping array
reshape = arr.reshape(3, 2)
print(reshape)

[[1 2]
 [3 4]
 [5 6]]


Reshape and Transposing - Transposing Arrays

In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Transposing array
transpose = arr.T
print(transpose)

[[1 4]
 [2 5]
 [3 6]]


Aggregation Function - Sum and Mean

In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Sum of all element
print(np.sum(arr))

21


In [43]:
# Sum along columns
print(np.sum(arr, axis=0))

[5 7 9]


In [44]:
# Sum along rows
print(np.sum(arr, axis=1))

[ 6 15]


In [45]:
# Mean of all elements
print(np.mean(arr))

3.5


In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Mininum value
print(np.min(arr))

1


In [47]:
# Maximum value
print(np.max(arr))

6


In [48]:
#index of minimum value
print(np.argmin(arr))

0


In [49]:
#index of maximun value
print(np.argmax(arr))

5
